EcomProjectonline/ecomProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



EcomProjectonline/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
]

EcomProjectonline/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(max_length=255,unique=True)
    description = models.TextField(unique=True)
    image = models.ImageField(upload_to='category',blank=True)


    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(max_length=255,unique=True)
    desciption = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name



EcomProjectonline/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import *


# Create your views here.

def allProdCat(request,c_slug=None):
    c_page = None
    products =None

    if c_slug !=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products = Product.objects.all().filter(category=c_page,available=True)
    else:
        products = Product.objects.all().filter(available=True)
    return render(request,'category.html',{'category':c_page,'products':products})


EcomProjectonline/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block description %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div>
    {% include 'header.html'%}
    {% include 'navbar.html'%}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html'%}
</body>
</html>

EcomProjectonline/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{ category.description|truncatewords:155}}
  {% else %}
      welcome to ABC
  {% endif %}
{% endblock %}

{% block title %}
{% if category %}
    {{category.name}}
  {% else %}
  See our new product
  {% endif %}

{% endblock %}

{% block content %}
{% if category %}
<div>
  <div>
    <p><a href="{% url 'shop:allProdCat'%}">our all products</a></p>
  </div>
</div>
{% endif %}
<div>
  {% if category %}
  <img src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
  <h1>{{category.name}}</h1>
  <p>{{category.description}}</p>
</div>
{% else %}
<div>
<img src="{% static 'img/banner.png' %}" alt="our product image">
  </div>
<br>
<div>
  <h1>oUR PRODUCT COLLECTONS</h1>
  <p>orem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. It's also called placeholder (or filler) text. It's a convenient tool for mock-ups. It helps to outline the visual elements of a document or presentation,</p>
</div>
{% endif %}
<div>
  <div>
    {% for product in products %}
    <div>
    <div>
      <a href=""><img src="{{product.image.url}}" alt="{{product.name}}"></a>
      <div>
        <h4>{{product.name}}</h4>
        <p>{{product.price}}</p>
      </div>
    </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}


EcomProjectonline/templates/footer.html
<div>
    <p>&copy; WishWe tech private limited. All rights Reserved</p>
</div>

EcomProjectonline/templates/header.html
{% load static %}
<header>
  <center>
    <img src="{% static 'img/logo.png'%}" alt="mainlogo">
  </center>
</header>



EcomProjectonline/templates/navbar.html

<nav>
  <ul>
    <li><a href="{% url 'shop:allProdCat' %}">All Products</a></li>
    {% for cat in links %}
    <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
    {% endfor %}
    <li>Your Cat</li>
  </ul>
</nav>

